general:
  slug: python-project
  source_name: src
  description: Python Project Description
  version: 0.1.0
  author: Diego Martinez
  license: MIT # available: MIT, Apache, GPL
  python_version: 3.13 # available: 3.10, 3.11, 3.12, 3.13
  dependency_manager: uv # available: uv, pdm
dependencies:
  - name: ty
    version: latest # available: latest, specific version
    is_dev: true # true or false
    group: lint
  - name: pytest
    version: latest # available: latest, specific version
    is_dev: true # true or false
    group: test
  - name: fastapi
    version: latest
    is_dev: false # true or false
git:
  initialize: true # true or false
  username: dimanu-py
  email: dimanu.py@gmail.com
template:
  name: domain_driven_design # available: domain_driven_design, clean_architecture, standard_project, custom
  bounded_context: backoffice # only if template is domain_driven_design
  aggregate_name: user # only if template is domain_driven_design
  built_in_features:
    - value_objects
    - github_actions
    - makefile
    - logger
    - event_bus
    - async_sqlalchemy
    - async_alembic
    - fastapi_application
    