[project]
name = "python-template"
version = "0.4.0"
description = "Python template for projects"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sphinx>=8.1.3",
    "myst-parser>=4.0.0",
    "sphinx-wagtail-theme>=6.4.0",
    "typer>=0.15.1",
    "jinja2>=3.1.5",
    "questionary>=2.1.0",
    "commitizen>=4.2.2",
]
