name: Install Python and setup environment

inputs:
  python-version:
    description: 'The version of Python to use'
    required: false
    default: {{ general.python_version }}
outputs: {}
runs:
  using: composite
  steps:
    - name: 🐍 Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: {% raw %}${{ inputs.python-version }}{% endraw %}

    - name: 🔨 Install dependency manager
      run: python -m pip install {{ general.dependency_manager }}
      shell: bash

    - name: 📦 Install dependencies
      run: |
        uv sync --all-groups
        {% if "precommit_hook" in template.built_in_features %}
        uv run -m pre_commit install
        {% endif %}
      shell: bash
