name: Bump version

on:
  push:
    branches:
      - main
      - develop

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CODENET_TOKEN }}
          fetch-depth: 0
      - name: Bump version and update changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.CODENET_TOKEN }}