name: Run tests and linting

on:
  pull_request:

permissions:
  contents: write
  id-token: write

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: ./.github/actions/python_setup
      - name: Check linting
        id: check_lint
        run: uvx ruff check --exclude "instant_python/templates" instant_python test
        continue-on-error: true
      - name: Auto fix lint errors
        id: fix_lint
        if: ${{ steps.check_lint.outcome == 'failure' }}
        run: uvx ruff check --fix --exclude "instant_python/templates" instant_python test
      - name: Commit lint fixes
        if: ${{ steps.fix_lint.outcome == 'success' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "🚨 chore: fix linting issues via GitHub Actions"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check linting again
        run: uvx ruff check --exclude "instant_python/templates" instant_python test

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: ./.github/actions/python_setup
      - name: Check code format
        id: check_format
        run: uvx ruff format --check --exclude "instant_python/templates" instant_python test
        continue-on-error: true
      - name: Auto format code
        id: format_code
        if: ${{ steps.check_format.outcome == 'failure' }}
        run: uvx ruff format --exclude "instant_python/templates" instant_python test
      - name: Commit formatted code
        if: ${{ steps.format_code.outcome == 'success' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "🎨 style: format code via GitHub Actions"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check code format again
        run: uvx ruff format --check --exclude "instant_python/templates" instant_python test

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [lint, format]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python_setup
      - name: Install test dependencies
        run: uv pip install pytest pytest-cov
      - name: Run tests
        run: uv run pytest --cov=instant_python --cov-report=xml --cov-report=html --cov-report=term-missing test -ra
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          name: codecov-coverage
